spring:
  config:
    import:
      - auth.yml
      - datasource.yml

  sql:
    init:
      platform: h2
      mode: embedded

  # jpa settings
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

    open-in-view: false
